# Generated by Django 5.0.1 on 2024-01-06 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000000000)]),
        ),
    ]
