# Generated by Django 5.0.1 on 2024-01-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_employee_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
